apiVersion: v1
kind: Service
metadata:
  name: db-agent
  namespace: db-agent
  labels:
    app: db-agent
spec:
  type: LoadBalancer
  selector:
    app: db-agent
  ports:
    - name: http
      port: 80
      targetPort: 8501
